language: rust
matrix:
  include:
    - os: linux
      env: TARGET=armv7-unknown-linux-gnueabihf
      rust: stable
      dist: trusty
    - os: linux
      env: TARGET=x86_64-apple-darwin
      rust: stable
      dist: trusty
    - os: linux
      env: TARGET=i686-unknown-linux-gnu
      rust: stable
      dist: trusty
    - os: linux
      env: TARGET=i686-unknown-linux-musl
      rust: stable
      dist: trusty
    - os: linux
      env: TARGET=armv7-unknown-linux-gnueabihf
      rust: nightly
      dist: trusty
    - os: linux
      env: TARGET=x86_64-apple-darwin
      rust: nightly
      dist: trusty
    - os: linux
      env: TARGET=i686-unknown-linux-gnu
      rust: nightly
      dist: trusty
    - os: linux
      env: TARGET=i686-unknown-linux-musl
      rust: nightly
      dist: trusty
    - os: osx
      rust: stable
    - os: osx
      rust: nightly
script:
  - rustc --version
  - cargo install clippy || touch clippy_failed
  - RUST_BACKTRACE=1 cargo build
  - if [ ! -f clippy_failed ]; then cargo clippy; fi
  - if [ ! -f clippy_failed ]; then cargo bench; fi
  - RUST_BACKTRACE=1 cargo test
  - cd examples
  - RUST_BACKTRACE=1 cargo build
  - if [ ! -f ../clippy_failed ]; then cargo clippy; fi
  - cd ..
  - make
  - LD_LIBRARY_PATH=./target/debug ./simple
