[package]
name = "sysinfo"
version = "0.2.1"
authors = ["guillaume1.gomez@gmail.com"]

description = "Library to handle processus"
repository = "https://github.com/GuillaumeGomez/sysinfo"
license = "LGPL-3.0+"

build = "build.rs"

[dependencies]
libc = "^0.2"

[lib]
name = "sysinfo"
crate_type = ["rlib"]
path = "src/sysinfo.rs"

[target.'cfg(target_os = "macos")'.sysinfo]
links = "IOKit.framework"
