[package]
name = "sysinfo"
version = "0.3.19"
authors = ["Guillaume Gomez <guillaume1.gomez@gmail.com>"]

description = "Library to handle processes"
repository = "https://github.com/GuillaumeGomez/sysinfo"
license = "LGPL-3.0+"
readme = "README.md"

categories = ["filesystem", "os", "os::macos-apis", "os::unix-apis"]

build = "build.rs"

[dependencies]
libc = "^0.2"
cfg-if = "0.1"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["fileapi", "handleapi", "ioapiset", "minwindef", "pdh", "psapi", "synchapi", "sysinfoapi", "winbase", "winerror", "winioctl", "winnt"] }

[lib]
name = "sysinfo"
crate_type = ["rlib", "cdylib"]
path = "src/sysinfo.rs"

[features]
c-interface = []

[badges]
travis-ci = { repository = "GuillaumeGomez/sysinfo" }
appveyor = { repository = "GuillaumeGomez/sysinfo", service = "github" }
