[package]
name = "sysinfo"
version = "0.2.5"
authors = ["guillaume1.gomez@gmail.com"]

description = "Library to handle processes"
repository = "https://github.com/GuillaumeGomez/sysinfo"
license = "LGPL-3.0+"

categories = ["filesystem", "os", "os::macos-apis", "os::unix-apis"]

build = "build.rs"

[dependencies]
libc = "^0.2"

[lib]
name = "sysinfo"
crate_type = ["rlib"]
path = "src/sysinfo.rs"

[badges]
travis-ci = { repository = "GuillaumeGomez/sysinfo" }
appveyor = { repository = "GuillaumeGomez/sysinfo", service = "github" }
