[package]
name = "sysinfo"
version = "0.1.11"
authors = ["guillaume1.gomez@gmail.com"]

description = "Library to handle processus"
repository = "https://github.com/GuillaumeGomez/sysinfo"
license = "LGPL-3.0+"

[dependencies]
libc = "^0.2"

[lib]
name = "sysinfo"
crate_type = ["rlib"]
path = "src/sysinfo.rs"
