[package]
name = "sysinfo-examples"
version = "0.0.1"
authors = ["guillaume1.gomez@gmail.com"]

[dependencies.sysinfo]
path = ".."

[dependencies]
libc = "^0.2"

[[bin]]
name = "simple"
path = "src/simple.rs"